version: '3'
services:
  airflow:
    image: apache/airflow:2.9.1
    command: standalone
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    volumes:
      - ./dags:/opt/airflow/dags
      - ./requirements.txt:/requirements.txt
    ports:
      - "8080:8080"
